akka {
  loglevel = INFO
  stdout-loglevel = INFO
  log-config-on-start = off

  actor {
    provider = local
  }
}

registry-dispatcher {
  type = Dispatcher
  throughput = 30
  throughput-deadline-time = 0ms
}

comments-dispatcher {
  type = Dispatcher
  throughput = 50
  throughput-deadline-time = 0ms
}

sentiment-dispatcher {
  type = ForkJoinDispatcher
  throughput = 5

  dedicated-thread-pool {
    thread-count = 2
    threadtype = background
  }
}